
dist: trusty

language: java

node_js:
  - "10"

addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN

jdk:
  - oraclejdk11

script:
  - Xvfb :5 -screen 0 800x600x24 &
  - export DISPLAY=:5
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  



