
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Deploy JAR') 
        {
            steps 
            {
                echo 'Configuring...'

                sh '''
                    pwd
                    ls -ltrh
                    cd server/files/src/main/ansible
                    mvn install 
                    cp ${ansible_inventory_path} .
                    ls -ltrh
                    ansible-playbook deploy-jar.yml -i ansible-betoland.inventory -l inspiron
                '''
            }
        }
    }
}
