
pipeline 
{
    agent
    {
        label 'master'

        node('master') 
        {
            env.JAVA_HOME="${tool 'Java11'}"
            env.PATH="${env.JAVA_HOME}/bin:${env.PATH}"
            sh 'java -version'
        }
    }

    stages 
    {
        stage('Deploy JAR') 
        {
            steps 
            {
                echo 'Configuring...'

                sh '''
                    pwd
                    ls -ltrh
                    cd server/files/
                    mvn install 
                    cd src/main/ansible
                    cp ${ansible_inventory_path} .
                    ls -ltrh
                    ansible-playbook deploy-jar.yml -i ansible-betoland.inventory -l inspiron
                '''
            }
        }
    }
}
