
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Deploy JAR') 
        {
            tools
            {
                jdk "Java11"
            }
            steps 
            {
                echo 'Configuring...'

                sh '''
                    pwd
                    ls -ltrh
                    cd server/files/
                    mvn package
                    mvn -P distribution -DskipTests install
                    cd src/main/ansible
                    cp ${ansible_inventory_path} .
                    ls -ltrh
                    ansible-playbook deploy-jar.yml -i ansible-betoland.inventory -l ${hostLimit} --extra-vars "onebeartoeCronUser=${cronUser} other=123"
                '''
            }
        }
    }
}
