
- name: Create a cron job for the image server.
  cron:
    name: "image sever job on reboot"
    special_time: reboot
    job: "/opt/onebeartoe/imaging/server/files/run.sh > /opt/onebeartoe/imaging/server/files/server.log 2>&1 &"
