
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Configure Cron Table Entry for Imaging File Server') 
        {
            steps 
            {
                echo 'Configuring...'

                sh '''
                    pwd
                    ls -ltrh
                    cd server/files/src/main/ansible
                    cp ${ansible_inventory_path} .
                    ls -ltrh
                    ansible-playbook cron.yml -i ansible-betoland.inventory -l ${hostLimit} --extra-vars "onebeartoeCronUser=${cronUser} other=123"
                '''
            }
        }
    }
}