
- name: Create the directory for the application binaries.
  file:
    path: "/opt/onebeartoe/imaging/server/files"
    state: directory
    owner: "{{onebeartoeCronUser}}"
    group: "{{onebeartoeCronUser}}"




- name: "Local Debug: who am I"
  shell: whoami
  register: localWhoami
- debug: msg="{{ localWhoami.stdout }}"
- debug: msg="{{ localWhoami.stderr }}"




- name: "Local Debug: M2 Repository Listing"
  local_action: shell pwd; ls -la ~/.m2/repository/org/onebeartoe/
  become: false  
  register: m2Listing
- debug: msg="{{ m2Listing.stdout }}"
- debug: msg="{{ m2Listing.stderr }}"




- name: "Local Debug: pwd"
  local_action: shell pwd; ls -la ../../../
  become: false  
  register: localPwd
- debug: msg="{{ localPwd.stdout }}"
- debug: msg="{{ localPwd.stderr }}"





- name: "Debug: who am I"
  shell: whoami
  register: romoteWhoami
- debug: msg="{{ romoteWhoami.stdout }}"
- debug: msg="{{ romoteWhoami.stderr }}"

- name: "Debug: who am I"
  shell: whoami

- name: Copy the JAR file to the target host.
  copy:
    src: ~/.m2/repository/org/onebeartoe/imaging/files/0.0.1-SNAPSHOT/files-0.0.1-SNAPSHOT.jar
    dest: /opt/onebeartoe/imaging/server/files/
    owner: "{{onebeartoeCronUser}}"
    group: "{{onebeartoeCronUser}}"





- name: Copy the run script to the target host.
  copy:
    src: files/run.sh
    dest: /opt/onebeartoe/imaging/server/files/
    owner: "{{onebeartoeCronUser}}"
    group: "{{onebeartoeCronUser}}"



- name: Copy the run script to the target host.
  copy:
    src: files/application.properties
    dest: /opt/onebeartoe/imaging/server/files/
    owner: "{{onebeartoeCronUser}}"
    group: "{{onebeartoeCronUser}}"
